#camera parameters
camera/horizontal: deg(37.6)
camera/vertical: deg(29.3)
camera/pitch: deg(0)
  #maximum and minimum sensor distance in mm
camera/max_dist: 555.0
camera/min_dist: 325.0
  #minimum incidence angle in degrees
camera/incidence_angle: 45

#rotorcraft parameters
rotorcraft/maxSpeed: 1.0
rotorcraft/maxAngularSpeed: 0.5

#mesh parameters
mesh/path: "/home/chris/catkin_ws/src/StructuralInspectionPlanner/request/meshes/BigBen.stl"
          #Make independent from my own file system
mesh/target_resolution_coarse: 0.02
mesh/target_resolution_fine: 0.01

#display
display/progress: true

#algorithm
  #percentage of surface area that needs to be covered by a view point to be considered further
algorithm/stop_criterion: 0.2
algorithm/sphere_sampling_points: 100