#camera parameters
camera/horizontal: deg(37.6)
camera/vertical: deg(29.3)
camera/pitch: deg(0)

#rotorcraft parameters
rotorcraft/maxSpeed: 1.0
rotorcraft/maxAngularSpeed: 0.5

#mesh parameters
mesh/path: "/home/chris/catkin_ws/src/StructuralInspectionPlanner/request/meshes/BigBen.stl"
mesh/target_resolution_coarse: 0.02
mesh/target_resolution_fine: 0.01
